"""Run the SQL models, then write public aggregate findings and the private target list."""

import csv
from pathlib import Path

import duckdb

from .ingest import DB, ROOT

SQL = Path(__file__).parent / "sql"
OUT = ROOT / "outputs"
PRIVATE = ROOT / "data" / "private"

BOUTIQUE_MIN, BOUTIQUE_MAX = 10, 50


def pct(n, d):
    return f"{100 * n / d:.0f}%" if d else "n/a"


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def run_models(con):
    for path in sorted(SQL.glob("*.sql")):
        print(f"  {path.name}")
        con.execute(path.read_text())


def report(con) -> str:
    q = lambda sql: con.execute(sql).fetchall()
    one = lambda sql: con.execute(sql).fetchone()

    md = ["# Findings", "", "_Generated by `build.py` from public SEC data. Aggregates only; no personal data._", ""]

    # --- coverage
    filled, total = one("SELECT count(has_admin), count(*) FROM fund_obs")
    lo, hi = one("SELECT min(filed_on), max(filed_on) FROM fund_obs")
    roster_file = one("SELECT string_agg(DISTINCT source_file, ', ' ORDER BY source_file) FROM roster")[0]
    md += ["## Data", "",
           f"- Fund-level rows (Schedule D 7.B.(1)): **{total:,}** across filings {lo} to {hi}; "
           f"administrator field answered on **{pct(filled, total)}**.",
           f"- Current status and size from the SEC adviser roster: `{roster_file}`.", ""]

    # --- self-administration by fund type, latest filing per adviser
    rows = q("""SELECT fund_type, count(*), count(*) FILTER (NOT has_admin)
                FROM fund_obs JOIN latest_filing USING (filing_id, regime)
                WHERE fund_type IS NOT NULL GROUP BY 1
                ORDER BY count(*) FILTER (NOT has_admin)::DOUBLE / count(*) DESC""")
    md += ["## Who runs their own close", "", "Share of funds reporting no outside administrator (latest filing per adviser):", "",
           table(["Fund type", "Funds", "No outside administrator"], [(t, f"{n:,}", pct(s, n)) for t, n, s in rows]), ""]

    # --- targeting funnel
    steps = [
        ("Advisers with >= 1 PE/RE fund", "n_pe_re > 0"),
        ("...still registered/exempt today", "n_pe_re > 0 AND active_now"),
        ("...US main office", "n_pe_re > 0 AND active_now AND country = 'United States'"),
        ("...private fund assets $20M-$500M", "n_pe_re > 0 AND active_now AND country = 'United States' AND private_fund_assets BETWEEN 20e6 AND 500e6"),
        ("...1-5 private funds", "n_pe_re > 0 AND active_now AND country = 'United States' AND private_fund_assets BETWEEN 20e6 AND 500e6 AND private_fund_count BETWEEN 1 AND 5"),
    ]
    funnel = [(label, f"{one(f'SELECT count(*) FROM adviser_profile WHERE {cond}')[0]:,}") for label, cond in steps]
    tiers = q("""SELECT tier, count(*), count(*) FILTER (all_audited), count(cco_name), count(website),
                        round(median(private_fund_assets) / 1e6)
                 FROM targets GROUP BY 1 ORDER BY 1""")
    md += ["## Target universe", "", table(["Step", "Advisers"], funnel), "",
           table(["Tier", "Advisers", "All PE/RE funds audited", "Named CCO", "Website", "Median private fund assets ($M)"],
                 [(t, n, a, pct(c, n), pct(w, n), m) for t, n, a, c, w, m in tiers]), "",
           "Tier A = every PE/RE fund self-administered · B = some · C = none (control group).", ""]

    # --- administrators
    n_admins = one("SELECT count(*) FROM administrators")[0]
    n_band = one(f"SELECT count(*) FROM administrators WHERE pe_re_funds BETWEEN {BOUTIQUE_MIN} AND {BOUTIQUE_MAX}")[0]
    top = q("SELECT administrator, pe_re_funds FROM administrators ORDER BY pe_re_funds DESC, administrator LIMIT 10")
    md += ["## Fund administrators (channel buyer)", "",
           f"- **{n_admins:,}** distinct US administrator names serve PE/RE funds of active advisers; "
           f"**{n_band}** serve {BOUTIQUE_MIN}-{BOUTIQUE_MAX} funds (boutique band, before removing bank/large-admin subsidiaries).", "",
           table(["Largest by PE/RE funds", "Funds"], top), ""]

    # --- backtest
    n, base = one("SELECT count(*), avg(switched::INT) FROM backtest")
    feats = []
    for f, label in [("f_audited", "Audited"), ("f_mid_size", "Adviser $20M-$500M"),
                     ("f_small_mgr", "Adviser 1-5 funds"), ("f_growing", "Fund assets +25% YoY")]:
        y = one(f"SELECT count(*), avg(switched::INT) FROM backtest WHERE {f}")
        no = one(f"SELECT count(*), avg(switched::INT) FROM backtest WHERE NOT {f}")
        feats.append((label, f"{y[0]:,}", f"{100 * (y[1] or 0):.1f}%", f"{100 * (no[1] or 0):.1f}%",
                      f"{(y[1] or 0) / no[1]:.2f}x" if no[1] else "n/a"))
    by_score = q("SELECT score, count(*), avg(switched::INT) FROM backtest GROUP BY 1 ORDER BY 1")
    hi_rate = one("SELECT avg(switched::INT) FROM backtest WHERE score >= 3")[0] or 0
    lo_rate = one("SELECT avg(switched::INT) FROM backtest WHERE score <= 1")[0] or 0
    winners = q("SELECT administrator, funds_won FROM switch_winners ORDER BY funds_won DESC, administrator LIMIT 10")
    md += ["## Backtest: does the score predict who buys fund administration?", "",
           f"Cohort: **{n:,}** self-administered PE/RE funds (base year 2014-2021, first eligible year per fund), "
           f"observed again 3 years later. **{100 * base:.1f}%** had hired an outside administrator.", "",
           "Score is pre-registered in `sql/03_backtest.sql` (1 point each, fixed before outcomes were examined).", "",
           table(["Signal", "Funds with signal", "Switch rate (with)", "Switch rate (without)", "Lift"], feats), "",
           table(["Score", "Funds", "Switched within 3 yrs"], [(s, f"{c:,}", f"{100 * r:.1f}%") for s, c, r in by_score]), "",
           f"**Score 3-4 vs 0-1: {100 * hi_rate:.1f}% vs {100 * lo_rate:.1f}% "
           f"({hi_rate / lo_rate:.1f}x lift).**" if lo_rate else "", "",
           "Caveat: funds that stopped reporting within 3 years (wound down, merged) are excluded, "
           "so this measures switching among survivors.", "",
           "v1 is kept as registered. A learned score tested out-of-time is in [score_v2.md](score_v2.md).", "",
           table(["Who won the switchers", "Funds"], winners), ""]

    # --- Form D
    nd, matched = one("""
        WITH fd AS (
            SELECT o.ACCESSIONNUMBER, upper(trim(i.ENTITYNAME)) AS name
            FROM raw_formd_offering o JOIN raw_formd_issuers i USING (ACCESSIONNUMBER)
            WHERE o.INVESTMENTFUNDTYPE IN ('Private Equity Fund', 'Other Investment Fund')
               OR o.INDUSTRYGROUPTYPE IN ('Other Real Estate', 'Commercial', 'Residential', 'REITS and Finance'))
        SELECT count(DISTINCT ACCESSIONNUMBER),
               count(DISTINCT ACCESSIONNUMBER) FILTER (name IN (SELECT DISTINCT upper(fund_name) FROM fund_obs))
        FROM fd""")
    md += ["## Form D as a freshness trigger", "",
           f"- {nd:,} PE / other-fund / real-estate Form D filings in the loaded quarters; "
           f"{pct(matched, nd)} match an ADV-reported fund by exact name. "
           "Form D is used as a 'something new happened' trigger, not as the targeting spine.", ""]
    return "\n".join(md)


def export_private(con):
    PRIVATE.mkdir(parents=True, exist_ok=True)
    path = PRIVATE / "targets.csv"
    cur = con.execute("""SELECT tier, adviser_name, crd, regime, state, round(private_fund_assets / 1e6, 1) AS private_fund_assets_musd,
                                private_fund_count, n_pe, n_re, all_audited, cco_name, website, fund_detail_as_of
                         FROM targets ORDER BY tier, private_fund_assets DESC, crd""")
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([d[0] for d in cur.description])
        w.writerows(cur.fetchall())
    print(f"  private target list -> {path.relative_to(ROOT)}")


def main():
    with duckdb.connect(str(DB)) as con:
        print("Building models")
        run_models(con)
        OUT.mkdir(exist_ok=True)
        (OUT / "findings.md").write_text(report(con))
        print(f"  findings -> outputs/findings.md")
        export_private(con)


if __name__ == "__main__":
    main()
