"""Run the SQL models, then write public aggregate findings and the private target list."""

import csv
from pathlib import Path

import duckdb

from .ingest import DB, ROOT

SQL = Path(__file__).parent / "sql"
OUT = ROOT / "outputs"
PRIVATE = ROOT / "data" / "private"

BOUTIQUE_MIN, BOUTIQUE_MAX = 10, 50


def pct(n, d):
    return f"{100 * n / d:.0f}%" if d else "n/a"


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def run_models(con):
    for path in sorted(SQL.glob("*.sql")):
        print(f"  {path.name}")
        con.execute(path.read_text())


def report(con) -> str:
    q = lambda sql: con.execute(sql).fetchall()
    one = lambda sql: con.execute(sql).fetchone()

    md = ["# Findings", "", "_Generated by `build.py` from public SEC data. Summary stats only, no personal data._", "",
          "Terms used below: an *adviser* is the firm that manages one or more funds. *PE/RE* means private equity and "
          "real estate. A fund that reports no outside fund administrator does its own books, and is called "
          "*self-administered*.", ""]

    # --- coverage
    filled, total = one("SELECT count(has_admin), count(*) FROM fund_obs")
    lo, hi = one("SELECT min(filed_on), max(filed_on) FROM fund_obs")
    roster_file = one("SELECT string_agg(DISTINCT source_file, ', ' ORDER BY source_file) FROM roster")[0]
    md += ["## Data", "",
           f"- Fund records (Form ADV, Schedule D 7.B.(1)): **{total:,}**, from filings dated {lo} to {hi}. "
           f"The administrator question is answered on **{pct(filled, total)}** of them.",
           f"- Which advisers are active today, and their current size, comes from the SEC's adviser list: `{roster_file}`.", ""]

    # --- self-administration by fund type, latest filing per adviser
    rows = q("""SELECT fund_type, count(*), count(*) FILTER (NOT has_admin)
                FROM fund_obs JOIN latest_filing USING (filing_id, regime)
                WHERE fund_type IS NOT NULL GROUP BY 1
                ORDER BY count(*) FILTER (NOT has_admin)::DOUBLE / count(*) DESC""")
    md += ["## Which funds do their own books", "", "Share of funds that report no outside administrator, using each adviser's latest filing:", "",
           table(["Fund type", "Funds", "No outside administrator"], [(t, f"{n:,}", pct(s, n)) for t, n, s in rows]), ""]

    # --- targeting funnel
    steps = [
        ("Advisers with at least one PE/RE fund", "n_pe_re > 0"),
        ("...still active today", "n_pe_re > 0 AND active_now"),
        ("...main office in the US", "n_pe_re > 0 AND active_now AND country = 'United States'"),
        ("...$20M–$500M in private funds", "n_pe_re > 0 AND active_now AND country = 'United States' AND private_fund_assets BETWEEN 20e6 AND 500e6"),
        ("...1–5 private funds", "n_pe_re > 0 AND active_now AND country = 'United States' AND private_fund_assets BETWEEN 20e6 AND 500e6 AND private_fund_count BETWEEN 1 AND 5"),
    ]
    funnel = [(label, f"{one(f'SELECT count(*) FROM adviser_profile WHERE {cond}')[0]:,}") for label, cond in steps]
    tiers = q("""SELECT tier, count(*), count(*) FILTER (all_audited), count(cco_name), count(website),
                        round(median(private_fund_assets) / 1e6)
                 FROM targets GROUP BY 1 ORDER BY 1""")
    md += ["## Narrowing to the target list", "", table(["Step", "Advisers"], funnel), "",
           f"Those {funnel[-1][1]} advisers are split into tiers by how many of their PE/RE funds do their own books.", "",
           table(["Tier", "Advisers", "All PE/RE funds audited", "Compliance officer named", "Website", "Median private fund assets ($M)"],
                 [(t, n, a, pct(c, n), pct(w, n), m) for t, n, a, c, w, m in tiers]), "",
           "Tier A = every PE/RE fund does its own books · B = some do · C = none do (kept as a comparison group).", ""]

    # --- administrators
    n_admins = one("SELECT count(*) FROM administrators")[0]
    n_band = one(f"SELECT count(*) FROM administrators WHERE pe_re_funds BETWEEN {BOUTIQUE_MIN} AND {BOUTIQUE_MAX}")[0]
    top = q("SELECT administrator, pe_re_funds FROM administrators ORDER BY pe_re_funds DESC, administrator LIMIT 10")
    md += ["## Fund administrators (a possible sales channel)", "",
           f"- **{n_admins:,}** different US administrators serve the PE/RE funds of active advisers. "
           f"**{n_band}** of them serve {BOUTIQUE_MIN}–{BOUTIQUE_MAX} funds, a rough cut for smaller boutique firms "
           "(some are still arms of banks or large administrators).", "",
           table(["Largest, by PE/RE funds served", "Funds"], top), ""]

    # --- backtest
    n, base = one("SELECT count(*), avg(switched::INT) FROM backtest")
    feats = []
    for f, label in [("f_audited", "Audited"), ("f_mid_size", "Adviser $20M-$500M"),
                     ("f_small_mgr", "Adviser 1-5 funds"), ("f_growing", "Fund assets up 25%+ in a year")]:
        y = one(f"SELECT count(*), avg(switched::INT) FROM backtest WHERE {f}")
        no = one(f"SELECT count(*), avg(switched::INT) FROM backtest WHERE NOT {f}")
        feats.append((label, f"{y[0]:,}", f"{100 * (y[1] or 0):.1f}%", f"{100 * (no[1] or 0):.1f}%",
                      f"{(y[1] or 0) / no[1]:.2f}x" if no[1] else "n/a"))
    by_score = q("SELECT score, count(*), avg(switched::INT) FROM backtest GROUP BY 1 ORDER BY 1")
    hi_rate = one("SELECT avg(switched::INT) FROM backtest WHERE score >= 3")[0] or 0
    lo_rate = one("SELECT avg(switched::INT) FROM backtest WHERE score <= 1")[0] or 0
    winners = q("SELECT administrator, funds_won FROM switch_winners ORDER BY funds_won DESC, administrator LIMIT 10")
    md += ["## Backtest: did the v1 score predict which funds hired an administrator?", "",
           f"Funds tested: **{n:,}** PE/RE funds that did their own books in some year from 2014 to 2021 "
           f"(each fund counted once, in its first such year), then checked again 3 years later. "
           f"**{100 * base:.1f}%** had hired an outside administrator by then.", "",
           "The score was written down in `sql/03_backtest.sql` before any results were looked at: 1 point per signal.", "",
           table(["Signal", "Funds with signal", "Hired admin (with signal)", "Hired admin (without)", "Ratio"], feats), "",
           table(["Score", "Funds", "Hired admin within 3 yrs"], [(s, f"{c:,}", f"{100 * r:.1f}%") for s, c, r in by_score]), "",
           f"**Score 3–4 vs 0–1: {100 * hi_rate:.1f}% vs {100 * lo_rate:.1f}% hired an administrator "
           f"({hi_rate / lo_rate:.1f}x).** Barely better than random." if lo_rate else "", "",
           "Caveat: funds that stopped filing within 3 years (closed or merged) are left out, "
           "so these rates only cover funds that were still around.", "",
           "The v1 score is left as it was first written. A score learned from the data and tested on later years "
           "is in [score_v2.md](score_v2.md). A test against 2025–26 filings is in [refresh.md](refresh.md).", "",
           table(["Administrators that won the most of these funds", "Funds"], winners), ""]

    # --- Form D
    nd, matched = one("""
        WITH fd AS (
            SELECT o.ACCESSIONNUMBER, upper(trim(i.ENTITYNAME)) AS name
            FROM raw_formd_offering o JOIN raw_formd_issuers i USING (ACCESSIONNUMBER)
            WHERE o.INVESTMENTFUNDTYPE IN ('Private Equity Fund', 'Other Investment Fund')
               OR o.INDUSTRYGROUPTYPE IN ('Other Real Estate', 'Commercial', 'Residential', 'REITS and Finance'))
        SELECT count(DISTINCT ACCESSIONNUMBER),
               count(DISTINCT ACCESSIONNUMBER) FILTER (name IN (SELECT DISTINCT upper(fund_name) FROM fund_obs))
        FROM fd""")
    md += ["## Form D: only a sign that something happened", "",
           f"- {nd:,} Form D filings from PE, real estate and other funds in the quarters loaded. "
           f"Only {pct(matched, nd)} match a Form ADV fund by exact name, so Form D is used as a sign that "
           "something new happened at a firm, not to build the target list.", ""]
    return "\n".join(md)


def export_private(con):
    PRIVATE.mkdir(parents=True, exist_ok=True)
    path = PRIVATE / "targets.csv"
    cur = con.execute("""SELECT tier, adviser_name, crd, regime, state, round(private_fund_assets / 1e6, 1) AS private_fund_assets_musd,
                                private_fund_count, n_pe, n_re, all_audited, cco_name, website, fund_detail_as_of
                         FROM targets ORDER BY tier, private_fund_assets DESC, crd""")
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow([d[0] for d in cur.description])
        w.writerows(cur.fetchall())
    print(f"  private target list -> {path.relative_to(ROOT)}")


def main():
    with duckdb.connect(str(DB)) as con:
        print("Building models")
        run_models(con)
        OUT.mkdir(exist_ok=True)
        (OUT / "findings.md").write_text(report(con))
        print(f"  findings -> outputs/findings.md")
        export_private(con)


if __name__ == "__main__":
    main()
